groups:
  md_5:
  - admin
disabled_commands:
- find
player_limit: -1
stats: aa2fcdef-b0c9-487d-a815-973112846d66
permissions:
  default:
  - bungeecord.command.server
  - bungeecord.command.list
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
listeners:
- max_players: 1
  fallback_server: lobby
  host: 0.0.0.0:25577
  bind_local_address: true
  ping_passthrough: false
  tab_list: GLOBAL_PING
  default_server: lobby
  forced_hosts:
    pvp.md-5.net: pvp
  tab_size: 60
  force_default_server: false
  motd: '&1Another Bungee server'
  query_enabled: false
  query_port: 25577
timeout: 30000
connection_throttle: 4000
servers:
  lobby:
    address: localhost:25565
    restricted: false
    motd: '&1Just another BungeeCord - Forced Host'
online_mode: true
